# Generated by Django 3.0.8 on 2020-07-07 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstaidkit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicament',
            old_name='id_firstaidkit',
            new_name='firstaidkit_id',
        ),
        migrations.AlterField(
            model_name='medicament',
            name='date_of_purchase',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
