# Generated by Django 3.0.8 on 2020-07-07 10:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstaidkit', '0002_auto_20200707_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_tablets', models.IntegerField(default=0)),
                ('date_of_used', models.DateField(blank=True, default=datetime.datetime.now)),
                ('is_used', models.BooleanField(default=False)),
                ('is_utylized', models.BooleanField(default=False)),
                ('firstaidkit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('medicament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstaidkit.Medicament')),
            ],
        ),
    ]
