# Generated by Django 3.0.8 on 2020-07-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstaidkit', '0003_medicinemanagement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicament',
            old_name='firstaidkit_id',
            new_name='firstaidkit',
        ),
        migrations.RenameField(
            model_name='medicinemanagement',
            old_name='firstaidkit_id',
            new_name='firstaidkit',
        ),
        migrations.RenameField(
            model_name='medicinemanagement',
            old_name='medicament_id',
            new_name='medicament',
        ),
    ]
