# Generated by Django 3.0.8 on 2020-07-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstaidkit', '0004_auto_20200707_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='number_of_tablets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicinemanagement',
            name='number_of_tablets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
