# Generated by Django 3.0.8 on 2020-07-08 11:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstaidkit', '0005_auto_20200707_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicament',
            old_name='number_of_tablets',
            new_name='number_of_tablets_or_ml',
        ),
        migrations.RenameField(
            model_name='medicinemanagement',
            old_name='number_of_tablets',
            new_name='number_of_tablets_or_ml',
        ),
        migrations.CreateModel(
            name='Syrup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount_ml', models.PositiveIntegerField(default=0)),
                ('date_of_purchase', models.DateField(blank=True, default=datetime.datetime.now)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('firstaidkit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
