# Generated by Django 3.0.8 on 2020-07-08 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstaidkit', '0006_auto_20200708_1349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Syrup',
        ),
    ]
