# Generated by Django 3.0.8 on 2020-07-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstaidkit', '0007_delete_syrup'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinemanagement',
            name='is_used_absolute',
            field=models.BooleanField(default=False),
        ),
    ]
