# Generated by Django 3.0.8 on 2020-07-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstaidkit', '0008_medicinemanagement_is_used_absolute'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinemanagement',
            name='is_buyed',
            field=models.BooleanField(default=False),
        ),
    ]
