# Generated by Django 3.0.8 on 2020-07-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstaidkit', '0009_medicinemanagement_is_buyed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinemanagement',
            name='medicament',
            field=models.CharField(max_length=100),
        ),
    ]
